version: '3.8'

services:
  webapp:
    build: ./webapp
    command: npm run build
    volumes:
      - webapp:/webapp
  api:
    build: .
    command: sh ./entrypoint.sh
    volumes:
      - .:/code
      - type: volume
        source: webapp
        target: /code/webapp
        volume:
          nocopy: true
    ports:
      - "8000:8000"
    depends_on:
      - webapp
volumes:
  webapp:
